apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-v2
  namespace: default
spec:
  chart:
    repository: https://stefanprodan.github.io/podinfo
    name: podinfo
    version: 3.2.0
  values:
    service:
      type: ClusterIP
      httpPort: 9898
      externalPort: 9898
